version: '3'
services:
  nginx:
    depends_on:
      - db
      - wordpress
    container_name: inception_nginx
    build: requirements/NGINX/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - files:/var/www/html
    networks:
      - frontend
    restart : on-failure

  wordpress:
    container_name: inception_wp
    build: requirements/wordpress/
    volumes:
      - files:/var/www/html
    networks:
      - frontend
      - backend
    expose:
      - "9000"
    env_file:
     - .env
    restart : on-failure

  db:
    container_name: inception_db
    build: requirements/mariaDB/
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    expose:
      - "3306"
    env_file:
      - .env
    restart : on-failure

  redis:
    container_name: inception_redis
    build: requirements/bonus/redis
    expose:
      - "6379"
    networks:
      - backend
    restart : on-failure

  ftp:
    container_name: inception_ftp
    build: requirements/bonus/ftp
    volumes:
      - files:/var/www/html
    networks:
      - backend
    env_file:
      - .env
    expose:
      - "20"
      - "21"
    restart : on-failure

  adminer:
    container_name: inception_adminer
    build: requirements/bonus/adminer
    depends_on:
      - db
    volumes:
      - files:/var/www/html
    networks:
      - backend
    restart : on-failure

  static:
    container_name: inception_static
    build: requirements/bonus/static
    volumes:
      - files:/var/www/html
    networks:
      - frontend
      - backend
    restart : on-failure
  
  compose_ui:
      container_name: compose_ui
      image: francescou/docker-compose-ui:1.13.0
      restart: on-failure
      working_dir: /Inception
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}:/Inception
      ports:
        - "5000:5000"

networks:
  frontend:
  backend:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/edlim/data/db
  files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/edlim/data/wordpress