version: '3'
services:
  nginx:
    depends_on:
      - db
      - wordpress
    container_name: inception_nginx
    build: requirements/NGINX/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - files:/var/www/html
    networks:
      - frontend

  wordpress:
    container_name: inception_wp
    build: requirements/wordpress/
    volumes:
      - files:/var/www/html
    networks:
      - frontend
      - backend
    expose:
      - "9000"

  db:
    container_name: inception_db
    build: requirements/mariaDB/
    volumes:
      - db:/foo
    networks:
      - backend
    expose:
      - "3306"
    env_file:
      - .env

networks:
  frontend:
  backend:

volumes:
  db:
  files: