version: '3'
services:
  nginx:
    depends_on:
      - db
      - wordpress
    container_name: inception_nginx
    build: requirements/NGINX/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - files:/var/www/html
    networks:
      - frontend

  wordpress:
    container_name: inception_wp
    build: requirements/wordpress/
    volumes:
      - files:/var/www/html
    networks:
      - frontend
      - backend
    expose:
      - "9000"
    env_file:
     - .env

  db:
    container_name: inception_db
    build: requirements/mariaDB/
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    expose:
      - "3306"
    env_file:
      - .env
  
  redis:
    container_name: inception_redis
    build: requirements/bonus/redis
    expose:
      - "6379"
    networks:
      - backend

  ftp:
    container_name: inception_ftp
    build: requirements/bonus/ftp
    volumes:
      - files:/var/www/html
    networks:
      - backend
    env_file:
      - .env
    expose:
      - "20"
      - "21"

networks:
  frontend:
  backend:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/edlim/data/db
  files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/edlim/data/wordpress